### ISSUE TITLE
Failed to activate the node-debugger package

### ISSUE THREAD

**Issue by esd100** [kiddkai/atom-node-debugger#184]
[Enter steps to reproduce below:]

1. open Atom
2. first error that pops up

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.7.0

### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module 'ramda'

Error: Cannot find module 'ramda'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/esd100/.atom/packages/node-debugger/lib/debugger.coffee:1:5)
    at Object.<anonymous> (/Users/esd100/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/esd100/.atom/packages/node-debugger/lib/node-debugger.coffee:2:14)
    at Object.<anonymous> (/Users/esd100/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "react",
      "source-preview-react"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.3
atom-beautify, vundefined
atom-jade, v0.3.0
atom-snippets, v0.1.1
atom-typescript, v10.1.3
autocomplete-clang, v0.9.4
autocomplete-php, v0.3.7
autocomplete-python, v1.8.2
autocomplete-ruby, v0.1.0
color-picker, v2.2.2
css-snippets, v0.9.0
file-icons, v1.7.17
ink, v0.4.4
jade-autocompile, v0.8.3
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
julia-client, v0.4.7
language-babel, v2.32.0
language-jade, v0.7.1
language-julia, v0.6.0
language-mongodb, v0.3.1
language-swift, v0.4.0
linter, v1.11.14
linter-eslint, v7.2.4
linter-swiftc, v2.0.0
meteor-api, v2.20.0
minimap, v4.24.7
node-debugger, v1.7.0
react-snippets, v0.4.2
source-preview-pug, v0.2.0

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
@esd100 how did you install the package? normally the atom package manager solves this but if you download the package manually you must run npm install

**Comment by Apollon77** [comment]
I have the same issue after upgrading to 1.28.0 beta ...


```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:866:28)
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.48 
atom-beautify 0.32.4 
atom-ide-debugger-node 0.7.1 
atom-ide-ui 0.11.2 
auto-indent 0.5.0 
autocomplete-clang 0.11.4 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
copy-with-syntax 0.0.3 
file-icons 2.1.20 
git-control 0.9.0 
git-plus 7.10.2 
git-time-machine 2.0.1 
gitlab 0.1.3-7 
ide-cpp 0.0.3 
ide-typescript 0.7.6 
intentions 1.1.5 
language-arduino 0.4.3 
language-cpp14 0.6.2 
language-ini 1.20.0 
language-ino 0.2.0 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-cpplint 2.0.1 
linter-gcc 0.7.1 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-split-diff 0.3.7 
node-debugger 1.10.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
pull-request 0.2.1 
remote-sync 4.1.8 
split-diff 1.5.2 
symbols-tree-view 0.14.0 
tabs-to-spaces 1.0.5 
tool-bar 1.1.7 
travis-ci-status 1.3.1 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

It also showed that packages needs to get rebuild and I did that, but I still get this error on start of Atom!
```

**Comment by timecode** [comment]
Same today after updating to 1.28.0 release

**Comment by stefanb2** [comment]
Same here after updating to 1.28.0 release on a Fedora 28 system. All installed packages updated to latest version.

Error message is slightly different though:

```
Cannot find module '_debugger'
Hide Stack Trace
Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/stefanb/.atom/packages/node-debugger/lib/debugger.coffee:5:12)
```

**Comment by Apollon77** [comment]
Because this one was closed I decided to open a new one at #261 ... same issue

**Comment by deed02392** [comment]
Just occurred for me after updating. Windows x64.

**Comment by meteormatt** [comment]
I can only disable this package.
<img width="857" alt="2018-06-29 6 53 18" src="https://user-images.githubusercontent.com/424475/42088894-bb7e452a-7bcd-11e8-86ca-06c3174ff4cd.png">

**Comment by owendall** [comment]
For the last few days.  Mac OS X 10.13.5.

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/debugger.coffee:5:12)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/node-debugger.coffee:2:14)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Object.<anonymous> (/Users/owendall/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)

**Comment by owendall** [comment]
Atom 1.28.0

**Comment by jerodfritz** [comment]
same.  Atom 1.28.0 OSX

**Comment by miiila** [comment]
Same here, Atom 1.28.0, OS X High Sierra 10.13.5

**Comment by alessandrocm** [comment]
Same, Atom 1.28.0 OSX High Sierra 10.13.4

**Comment by black-snow** [comment]
Why is this closed?

**Comment by Apollon77** [comment]
Because this one was closed I decided to open a new one at #261 ... same issue

**Comment by AlexanderLill** [comment]
Also happening for me. Atom crashing with the above error message.
OS X 10.13.5 (17F77)
Atom 1.28.0
```
Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
   [...]
```

**Comment by gneissguise** [comment]
[Enter steps to reproduce:]

1. Launch Atom
2. Message appears when Atom loads

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 18.04
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/snap/atom/167/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/167/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/snap/atom/167/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/167/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/snap/atom/167/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/snap/atom/167/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/snap/atom/167/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/snap/atom/167/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/snap/atom/167/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/snap/atom/167/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/snap/atom/167/usr/share/atom/resources/app/src/package.js:220:40)
    at measure (/snap/atom/167/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/snap/atom/167/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/snap/atom/167/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/snap/atom/167/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/snap/atom/167/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/snap/atom/167/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/snap/atom/167/usr/share/atom/resources/app/src/config.js:866:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-html-templates 0.1.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.5 
color-picker 2.3.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.22 
Hydrogen 2.5.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-clojure 1.2.0 
linter-csslint 2.0.1 
linter-eslint 8.4.1 
linter-gcc 0.7.1 
linter-joker 0.1.4 
linter-lein 0.1.1 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-pigments 0.2.2 
node-debugger 1.10.1 
nuclide 0.321.0 
open-html-in-browser 0.2.1 
pigments 0.40.2 
proto-repl 1.4.24 
react 0.18.0 
react-es6-snippets 0.3.0 
react-snippets 1.1.1 
styri-syntax 0.2.0 
```

**Comment by jerodfritz** [comment]
1. Launch Atom
2. Message appears when Atom loads

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.2
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-material-syntax-light 0.4.6 
atom-ternjs 0.17.2 
atom-typescript 11.0.3 
autocomplete-modules 1.6.7 
build 0.67.0 
busy 0.7.0 
editorconfig 2.2.2 
es6-javascript 1.0.0 
file-icons 2.0.16 
file-types 0.5.5 
fizzy 0.21.0 
hyperclick 0.1.3 
javascript-snippets 1.2.1 
language-apache 1.7.0 
language-babel 2.55.6 
language-ejs 0.4.0 
language-gradle 0.0.3 
linter 1.11.23 
linter-eslint 8.1.2 
monokai 0.22.0 
node-debugger 1.10.1 
php-cs-fixer 4.1.0 
Remote-FTP 1.1.3 
standard-formatter 2.8.0 
terminal-plus 0.14.5 
ti-alloy-related-plus 0.1.1 
titanium-alloy 0.13.8 
titanium-build 0.8.1 
```

**Comment by EddyTheDove** [comment]
[Enter steps to reproduce:]

1. Launch atom
2. Error message displayed

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
```

### Commands

```
     -0:55.8.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angular-jonpapa-snippets 0.7.0 
angular2-snippets 0.4.0 
angular2-snippets-atom 0.7.0 
angularjs 0.5.3 
atom-beautify 0.32.5 
atom-jade 0.3.0 
atom-jsx-transform 0.2.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 12.6.2 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
autocomplete-modules 2.1.0 
autocomplete-nunjucks 0.5.0 
blade-snippets 0.2.0 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.2 
color-picker 2.3.0 
docblockr 0.13.7 
edge 2.1.0 
intentions 1.1.5 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
jade 1.2.0 
jade-beautify 0.1.5 
language-blade 0.40.0 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
language-nunjucks 4.2.1 
language-typescript-grammars-only 1.6.0 
language-vue 0.23.1 
linter 2.2.0 
linter-jade 0.3.2 
linter-js-standard 5.1.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
open-recent 5.0.0 
platformio-ide-terminal 2.8.3 
react 0.18.0 
react-es6-snippets 0.3.0 
run-command 0.5.0 
term3 0.22.1 
vue-autocomplete 0.1.1 
vue-snippets 0.6.0 
```

**Comment by yaplas** [comment]
I just disabled node-debugger package :(

**Comment by jerodfritz** [comment]
@yaplas How did you disable the node-debugger package?

**Comment by yaplas** [comment]
@centogram search `node-debugger` in Preferences/Packages, you have a disable button there

**Comment by izargarian** [comment]
Disabling the node-debugger worked for me. Thanks.
